training:
  pde: Allen-Cahn
  pde_params: [1.5] # vector of params of the pde
  sys_mode: PINN
  distill_mode: Forgetting
  ewc_mode: Off
  # train_steps: 1000
  epochs: 100
  eval_every: 1 # in epochs
  seed: 8
  device: cpu
  experiment_name: PINN

hyperparams:
  mode: Optimize
  bc_weight: [0.001, 1.0]
  #ic_weight:
  phy_weight: [0.001, 1.0]
  # distill_weight: [0.001, 1.0]
  # ewc_weight: [0.001, 1.0]
  layers: [50, 50, 50, 50]
  lr_init: [1e-6, 1e-6]
  batch_size: [2048]

paths:
  datasets_dir: data
  models_dir: models/AllenCahnSingle15/PINNfull3
  train_dataset: train/15/full/random_dom.pth
  train_bc_dataset: train/15/full/random_bd.pth
  # train_ic_dataset:
  # distill_dataset:
  # distill_model:
  eval_dataset: val/15/full/random_dom.pth
  eval_bc_dataset: val/15/full/random_bd.pth
  # eval_ic_dataset:
  starting_model: models/AllenCahnSingle10/PINNfull2/trial0/model.pth