generation:
  pde_name: Allen-Cahn
  pde_params: [[0.0], [0.5], [1.0], [1.5], [2.0], [2.5], [3.0], [3.5]]

  seed: 70

  bd_mode: random
  dom_mode: random

  boundary: True
  domain: True

  ranges:
    x: [-1.0, 1.0]
    y: [-1.0, 1.0]
  
  bd_steps: [0.01, 0.01]
  dom_steps: [0.01, 0.01]

  n_rand_bound: 1024 # = max{sqrt(n_rand_dom) * 4, batch_size}
  n_rand_dom: 4096
  n_rand_bound_sub: 256 # = max{sqrt(n_rand_dom / 4) * 4, batch_size}

options:
  data_dir: data/train
  params_id: [00, 05, 10, 15, 20, 25, 30, 35]

subsets:
  top: [[-1.0, 1.0], [0.0, 1.0]]
  down: [[-1.0, 1.0], [-1.0, 0.0]]
  right: [[0.0, 1.0], [-1.0, 1.0]]
  left: [[-1.0, 0.0], [-1.0, 1.0]]
  top_left: [[-1.0, 0.0], [0.0, 1.0]]
  top_right: [[0.0, 1.0], [0.0, 1.0]]
  down_left: [[-1.0, 0.0], [-1.0, 0.0]]
  down_right: [[0.0, 1.0], [-1.0, 0.0]]