training:
  pde: Allen-Cahn
  pde_params: [0.0] # vector of params of the pde
  sys_mode: PINN
  distill_mode: Derivative
  ewc_mode: On 
  # train_steps: 1000
  epochs: 100
  eval_every: 1 # in epochs
  seed: 30
  device: cpu
  experiment_name: prova2

hyperparams:
  mode: Optimize
  bc_weight: [0.001, 1.0]
  #ic_weight:
  phy_weight: [0.001, 1.0]
  distill_weight: [0.0001, 0.01]
  ewc_weight: [0.0001, 0.01]
  layers: [50, 50, 50, 50]
  lr_init: [1e-6, 1e-4]
  batch_size: [2048]

paths:
  datasets_dir: data
  models_dir: models/AllenCahnSingle0/PINN1
  train_dataset: train/0/top_right/random_dom.pth
  train_bc_dataset: train/0/top_right/random_bd.pth
  # train_ic_dataset:
  distill_dataset: train/0/top_right/random_dom.pth
  distill_model: models/AllenCahnSingle0/PINN0/trial3/model.pth
  eval_dataset: val/0/top_right/random_dom.pth
  eval_bc_dataset: val/0/top_right/random_bd.pth
  # eval_ic_dataset:

  datasets_dir: data
  models_dir: models/AllenCahnSingle0/PINN2
  train_dataset: train/0/down_right/random_dom.pth
  train_bc_dataset: train/0/down_right/random_bd.pth
  # train_ic_dataset:
  distill_dataset: train/0/down_right/random_dom.pth
  distill_model: models/AllenCahnSingle0/PINN1/trial7/model.pth
  eval_dataset: val/0/down_right/random_dom.pth
  eval_bc_dataset: val/0/down_right/random_bd.pth
  # eval_ic_dataset:

  datasets_dir: data
  models_dir: models/AllenCahnSingle0/PINN3
  train_dataset: train/0/down_left/random_dom.pth
  train_bc_dataset: train/0/down_left/random_bd.pth
  # train_ic_dataset:
  distill_dataset: train/0/down_left/random_dom.pth
  distill_model: models/AllenCahnSingle0/PINN2/trial3/model.pth
  eval_dataset: val/0/down_left/random_dom.pth
  eval_bc_dataset: val/0/down_left/random_bd.pth
  # eval_ic_dataset: