training:
  pde: Allen-Cahn
  pde_params: [0.0] # vector of params of the pde
  sys_mode: PINN
  distill_mode: Forgetting
  ewc_mode: Off
  with_pde_params: False
  # train_steps: 1000
  epochs: 100
  eval_every: 1 # in epochs
  seed: 8
  device: cpu
  experiment_name: exp

hyperparams:
  mode: Optimize
  bc_weight: [3e-4, 3e-4] #[2e-2, 2e-2]/sqrt(n=4096)
  #ic_weight:
  phy_weight: [2e-6, 2e-6]
  #distill_weight: [0.001, 1.0]
  #ewc_weight: [0.001, 1.0]
  input_units: 2
  layers: [50, 50, 50, 50]
  lr_init: [1e-6, 5e-6, 1e-5, 5e-5, 1e-4, 5e-4, 1e-3]
  batch_size: [1024, 2048]
  pruner: "median"
  #threshold: 0.027
  #n_warmup_steps: 25
  n_trials: 10
  optimizer: Adam

paths:
  datasets_dir: data
  models_dir: models/step0/AllenCahnSingle0/PINNfullB3
  train_dataset: train/0/full/random_dom.pth
  train_bc_dataset: train/0/full/random_bd.pth
  # train_ic_dataset:
  # distill_model:
  #distill_dataset: train/0/full/random_dom.pth
  eval_dataset: val/0/full/random_dom.pth
  eval_bc_dataset: val/0/full/random_bd.pth
  # eval_ic_dataset:
  #starting_model: models/AllenCahnSingle0/PINNfull0ti/best_trial/model.pth